Make HawkPost i18n ready
whitesmith/hawkpost pull request #203
Opened 2016-10-21 22:33 UTC by jleroy

This PR make HawkPost ready to be fully translated.

2016-10-24 14:06 UTC, dethos commented
@jleroy thanks, this PR addresses issue #24. I will try to review it and give some feedback during this week.

2016-10-28 18:23 UTC, dethos requested changes
This is a good start to address issue #24 , but it needs some fixes. I commented the lines where I found some issues that prevent the project from running as expected, in order to make it easier to follow.
If you could also fix the conflict in `index.html` it would be nice.
Thank you for your contribution.

2016-10-28 18:23 UTC, dethos commented on boxes/models.py
> +        (ONQUEUE, _('OnQueue'),
a `)` is missing here

2016-10-28 18:23 UTC, dethos commented on humans/admin.py
> +        messages.success(request, _('All notifications enqueued for sending')
a `)` is missing here

2016-10-28 18:23 UTC, dethos commented on humans/views.py
> +                               ' We hope you comeback soon.')
a `)` is missing here

2016-10-28 18:23 UTC, dethos commented on humans/views.py
> +                             ' the current password.')
a `)` is missing here

2016-10-28 18:23 UTC, dethos commented on boxes/forms.py
> +                             'never expire.')
a `)` is missing here

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/box_list.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/box_submit.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/closed.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/success.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/about.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/help.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/index.html
> +{% load i18n %}
`extends` must be the first tag in the template

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/about.html
> +					<h1 class="text-dark  ">{% trans "Hawkpost</h1>
`trans` tag is not closed

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/help.html
> +                    <p>{% blocktrans %}For Thunderbird users, the common practice is to install a plugin called <a href="https://www.enigmail.net/index.php/en/" class="testelinks">Enigmail</a>, which
`blocktrans` should be closed with an `endblocktrans`

2016-10-28 18:23 UTC, dethos commented on pages/templates/pages/help.html
> +                    <p>{% blocktrans %}Check <a href="https://blog.jigsawpieces.me/2015/03/19/tutorial-how-to-setup-gpg4win-with-outlook-2013/" class="testelinks">this video for an Outlook tutorial</
`blocktrans` should be closed with an `endblocktrans`

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/box_list.html
> +        <p class="smalltext text-lightest text-mob-">{% blocktrans %}For others to be able to send you encrypted content through Hawkpost, you'll need to generate "boxes".{% blocktrans %}</p>
`blocktrans` should be closed using `endblocktrans`

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/box_list.html
> +                    <input class="btn-dark text outro" type="submit" value="{% trans "DELETE" %} />
`"` is missing

2016-10-28 18:23 UTC, dethos commented on boxes/templates/boxes/box_list.html
> +                    <input class="btn-dark text outro" type="submit" value="{% trans "CLOSE" %}/>
`"` is missing on attribute `value`

2016-10-30 06:52 UTC, jleroy commented
@dethos Thank you for your review. I've fixed all issues.
There is still a merge conflict in `pages/templates/pages/index.html` related to "extends" and "load" tags, but I don't see how to fix it without merging the PR.

2016-11-21 18:04 UTC, jleroy commented
@dethos Can you look at my last changes?

2016-12-09 13:14 UTC, dethos commented
@jleroy sorry for the delay, but we went through several changes recently and I had to postpone the review of this pull request. When #222 goes through, I will get back to this pull request, to review it and test it.

Regarding the conflicts, they will have to be fixed before I'm able to merge into master. (Perhaps you should update the branch with the most recent changes in the master branch)

2016-12-12 13:07 UTC, jleroy commented
@dethos: Can you ping me when you're ready to review this PR, so I can resolve conflicts? Thx.

2016-12-14 14:55 UTC, dethos commented
@jleroy I will review this pull request in the next couple of days and there are no other PR that can interfere with this one. So it might be a good time to fix the conflicts. Thanks.

2016-12-14 16:07 UTC, jleroy commented
@dethos : Rebase done.

2017-01-05 01:26 UTC, dethos requested changes
@jleroy first of all, sorry for the delay in my response/review.
After testing your new changes I still found several problems that "crash" the app. So I won't be able accept the PR as it is right now. Below are the issues I found.

2017-01-05 01:26 UTC, dethos commented on pages/templates/pages/index.html
The `{% block content %}` is missing (was removed) on this file

2017-01-05 01:26 UTC, dethos commented on pages/templates/pages/help.html
> +<<<<<<< HEAD
Some remains from a previous conflict

2017-01-05 01:26 UTC, dethos commented on pages/templates/pages/help.html
> +                    <p>{% blocktrans %}Check <a href="https://blog.jigsawpieces.me/2015/03/19/tutorial-how-to-setup-gpg4win-with-outlook-2013/" class="testelinks">this video for an Outlook tutorial</
We still need this `blocktrans` to be closed with an `endblocktrans`

2017-01-05 01:26 UTC, dethos commented on pages/templates/pages/help.html
> +                    <p>{% blocktrans %}For Thunderbird users, the common practice is to install a plugin called <a href="https://www.enigmail.net/index.php/en/" class="testelinks">Enigmail</a>, which
We still need this `blocktrans` to be closed with an `endblocktrans`

2017-01-05 01:26 UTC, dethos commented on boxes/templates/boxes/box_list.html
> +        <p class="smalltext text-lightest text-mob-">{% trans "For others to be able to send you encrypted content through Hawkpost, you'll need to generate "boxes"." %}</p>
`"boxes"` causes an error, since this it closes the string and is interpreted as a variable. Please use `\"boxes\"`.

2017-01-08 15:28 UTC, jleroy commented
@dethos: Rebased and fixed.

2017-01-15 21:10 UTC, dethos approved these changes

2017-01-15 21:20 UTC, dethos commented
@jleroy just tested the new changes and everything seems to be working as expected.
Thank you for your contribution. Will merge this PR now.

2017-01-15 21:20 UTC, merged

2017-01-15 21:45 UTC, jleroy commented
Thank you @dethos.