Settings final
whitesmith/hawkpost pull request #216
Opened 2016-11-04 18:35 UTC by MariCerv

- added class for radio button labels
- text fixes
-settings fixes for big screens

2016-11-04 23:57 UTC, rafaelferreira6 requested changes
minor timezone fix

---

fechar "width:100%;"

2016-11-05 00:02 UTC, rafaelferreira6 requested changes
close.html
l.9 - "TTHIS"

verified_email_required.html
l.13 - "EM-AIL"

2016-11-08 00:25 UTC, rafaelferreira6 approved these changes

2016-11-08 19:53 UTC, dethos commented
@MariCerv can you fix the conflict?

2016-11-11 12:51 UTC, merged