212 password change
whitesmith/hawkpost pull request #254
Opened 2017-10-03 15:06 UTC by Lobosque

Fixes #212 

* Updates `UpdateUserInfoForm` to accept password change;
* Add "Change Password" section in the settings forms;
* Modify the settings form javascript to work for N tabs

2017-10-03 15:17 UTC, Lobosque commented
@dethos How do you think the new password form should behave for users that registered using GithubOauth (there is no current password for these cases).

2017-10-03 19:00 UTC, Onumis commented on humans/templates/humans/update_user_form.html
> +                        {{ form.new_password2.errors }} {{ form.new_password1.label_tag }} {{ form.new_password1 }}
I think this is a typo, should be `{{ form.new_password1.errors }}`

2017-10-03 19:53 UTC, Lobosque commented
I did it on purpose to always display the same message to both of them!

On Oct 3, 2017 16:00, "Nuno Silva" <notifications@github.com> wrote:

> *@Onumis* commented on this pull request.
> ------------------------------
>
> In humans/templates/humans/update_user_form.html
> <https://github.com/whitesmith/hawkpost/pull/254#discussion_r142490487>:
>
> > @@ -65,6 +66,19 @@
>                      </div>
>                    </li>
>                    <li class="section" id="section3">
> +                    <div class="col-xxs-12 col-xs-12 col-md-12 start-xs">
> +                      <div class="form__block">
> +                        {{ form.current_password.errors }} {{ form.current_password.label_tag }} {{ form.current_password }}
> +                      </div>
> +                      <div class="form__block">
> +                        {{ form.new_password2.errors }} {{ form.new_password1.label_tag }} {{ form.new_password1 }}
>
> I think this is a typo, should be {{ form.new_password1.errors }}
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/whitesmith/hawkpost/pull/254#pullrequestreview-66860223>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA7IXlcWpOnpyF9sYQfv-dilnDERQgXkks5sooRXgaJpZM4PsRfq>
> .
>

2017-10-13 14:48 UTC, dethos commented
@Lobosque for users who signed up using Github, we should not display the change password tab or to make it clear, instead of the form a message could be displayed saying that since the used Oauth there is not need to update passwords.

By the way, thanks for your contribution. As soon as you hide or display the message I will make a full review and merge the PR (on a first look everything appears to be fine :+1: )

2017-10-13 15:18 UTC, dethos requested changes
After testing a bit I found a small issue. 

Also `#tab4` is missing here: https://github.com/whitesmith/hawkpost/pull/254/files#diff-634d4c9620895e0cdf312c07c3ad90b6R49

2017-10-13 15:18 UTC, dethos commented on humans/static/javascripts/update_user_form.js
> +  $(".sett__nav__item").click(function(evt) {
For some reason this event is not being added to `#tab4` (at least on Firefox)

2017-10-16 14:19 UTC, Lobosque reviewed
@dethos I added a commit to hide the change password section from github signups.
However I couldn't reproduce the tab problem. All of them worked just fine in both Chrome and Firefox.

2017-10-16 14:19 UTC, Lobosque commented on humans/static/javascripts/update_user_form.js
> +  $(".sett__nav__item").click(function(evt) {
I tested here on Firefox and it triggers the event just fine.
Maybe a version issue? Can you try again?

2017-10-16 21:57 UTC, dethos reviewed
Just a small observation

2017-10-16 21:57 UTC, dethos commented on humans/forms.py
> +        return super(UpdateUserInfoForm, self).__init__(*args, **kwargs)
Why this change? This is a Python 3 project, there is no need to call super using the old "style".

2017-10-16 21:57 UTC, dethos commented on humans/forms.py
> +        return super(UpdateUserInfoForm, self).save(commit=commit)
here super can also be changed to the new style

2017-10-16 21:58 UTC, dethos commented on humans/static/javascripts/update_user_form.js
> +  $(".sett__nav__item").click(function(evt) {
Just tested again, with different browsers and it is working fine. Not sure what was the problem the other time.

2017-10-16 22:24 UTC, dethos approved these changes

2017-10-16 22:25 UTC, merged